# Generated by Django 4.2.7 on 2023-11-08 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfissionalSaude",
            fields=[
                ("IDProfissional", models.AutoField(primary_key=True, serialize=False)),
                ("IDRamoProfissional", models.IntegerField()),
                ("CodigoProfissional", models.CharField(max_length=255)),
                ("NomeCompleto", models.CharField(max_length=255)),
                ("RG_CPF_CNPJ", models.CharField(max_length=18)),
                ("Telefone", models.CharField(max_length=20, null=True)),
                ("DataNascimento", models.DateTimeField()),
                ("FotoPerfil", models.TextField(null=True)),
                ("Abordagem", models.TextField(null=True)),
                ("Atendimento", models.CharField(max_length=255)),
                ("FaixaHorario", models.TextField()),
                ("EnderecoConsultorio", models.TextField(null=True)),
                ("CreatedAt", models.DateTimeField()),
                ("UpdatedAt", models.DateTimeField()),
                ("Active", models.BooleanField()),
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                ("IDPaciente", models.AutoField(primary_key=True, serialize=False)),
                ("NomeCompleto", models.CharField(max_length=255)),
                ("Telefone", models.CharField(max_length=20, null=True)),
                ("DataNascimento", models.DateTimeField(null=True)),
                ("Cidade", models.CharField(max_length=255, null=True)),
                ("Deficiencia", models.TextField(null=True)),
                ("Remedio", models.TextField(null=True)),
                ("Enfermidades", models.TextField(null=True)),
                ("Encaminhamento", models.TextField(null=True)),
                ("Cor", models.CharField(max_length=255, null=True)),
                ("CreatedAt", models.DateTimeField()),
                ("UpdatedAt", models.DateTimeField()),
                ("Active", models.BooleanField()),
                (
                    "IDProfissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.profissionalsaude",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("IDConsulta", models.AutoField(primary_key=True, serialize=False)),
                ("DataHoraConsulta", models.DateTimeField()),
                ("Atendimento", models.CharField(max_length=255)),
                ("Valor", models.FloatField(null=True)),
                ("Comprovante", models.TextField(null=True)),
                ("Comentarios", models.TextField(null=True)),
                ("Cor", models.CharField(max_length=255, null=True)),
                ("CreatedAt", models.DateTimeField()),
                ("UpdatedAt", models.DateTimeField()),
                ("Active", models.BooleanField()),
                (
                    "IDPaciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.paciente"
                    ),
                ),
                (
                    "IDProfissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.profissionalsaude",
                    ),
                ),
            ],
        ),
    ]
