# Generated by Django 4.2.7 on 2023-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissionalsaude",
            name="Abordagem",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
