# Generated by Django 4.2.7 on 2023-11-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_profissionalsaude_abordagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissionalsaude",
            name="FaixaHorario",
            field=models.CharField(max_length=255),
        ),
    ]
