# Generated by Django 4.2.7 on 2023-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_profissionalsaude_faixahorario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profissionalsaude",
            name="Abordagem",
            field=models.CharField(
                choices=[
                    ("psicanalitica", "Psicanalítica"),
                    ("comportamental", "Comportamental"),
                    ("cognitiva", "Cognitiva"),
                    ("humanista", "Humanista"),
                    ("biologica", "Biológica"),
                    ("evolucionista", "Evolucionista"),
                    ("sociocultural", "Socio-cultural"),
                    ("psicodinamica", "Psicodinâmica"),
                    ("ecologica", "Ecológica"),
                    ("experimental", "Experimental"),
                    ("clinica", "Clínica"),
                    ("psicossocial", "Psicossocial"),
                    ("outras", "Outras"),
                ],
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaude",
            name="Atendimento",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("remoto", "Remoto"),
                    ("hibrido", "Híbrido"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profissionalsaude",
            name="FaixaHorario",
            field=models.CharField(
                choices=[
                    ("madrugada", "Madrugada"),
                    ("matinal", "Matinal"),
                    ("vespertino", "Vespertino"),
                    ("noturno", "Noturno"),
                ],
                max_length=255,
            ),
        ),
    ]
