# Generated by Django 4.2.7 on 2023-11-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_profissionalsaude_abordagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="EstadoCivil",
            field=models.CharField(
                choices=[
                    ("solteiro", "Solteiro(a)"),
                    ("casado", "Casado(a)"),
                    ("divorciado", "Divorciado(a)"),
                    ("viuvo", "Viúvo(a)"),
                    ("separado", "Separado(a)"),
                    ("uniaoestavel", "União Estável (ou Convivência Marital)"),
                    ("casadoseparacao", "Casado(a) com Separação de Bens"),
                    (
                        "casadouniversal",
                        "Casado(a) sob Regime de Comunhão Universal de Bens",
                    ),
                    (
                        "casadoparcial",
                        "Casado(a) sob Regime de Comunhão Parcial de Bens",
                    ),
                    (
                        "casadofinal",
                        "Casado(a) sob Regime de Participação Final nos Aquestos",
                    ),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Atendimento",
            field=models.CharField(
                choices=[
                    ("presencial", "Presencial"),
                    ("remoto", "Remoto"),
                    ("indefinido", "Indefinido"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="Deficiencia",
            field=models.CharField(
                choices=[
                    ("defvisual", "Deficiência Visual"),
                    ("defauditiva", "Deficiência Auditiva"),
                    ("defmotora", "Deficiência Motora"),
                    ("defcognitiva", "Deficiência Cognitiva"),
                    ("defFalaLinguagem", "Deficiência de Fala e Linguagem"),
                    ("defpsicossocialmental", "Deficiência Psicossocial ou Mental"),
                    ("defcronicasaude", "Deficiência Crônica de Saúde"),
                    ("defsensorial", "Deficiência Sensorial"),
                    ("outra", "Outra"),
                ],
                default=1,
                max_length=1000,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="Encaminhamento",
            field=models.CharField(
                choices=[
                    ("medico", "Médico"),
                    ("escolar", "Escolar"),
                    ("profsaude", "Outros Profissionais de Saúde"),
                    ("empresarial", "Empresarial"),
                    ("assistsocial", "Assistência Social"),
                    ("profsaudemental", "Profissionais da Saúde Mental"),
                    ("autoprocura", "Autoprocura"),
                    ("recomendacao", "Recomendação"),
                    ("nenhumaOpcao", "Nenhuma das Opções"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="Enfermidades",
            field=models.CharField(
                choices=[
                    ("infecciosas", "Infecciosas"),
                    ("cardiovasculares", "Cardiovasculares"),
                    ("respiratorias", "Respiratórias"),
                    ("neurologicas", "Neurológicas"),
                    ("endocrinas", "Endócrinas"),
                    ("gastrointestinais", "Gastrointestinais"),
                    ("renais", "Renais"),
                    ("musculoesqueleticas", "Musculoesqueléticas"),
                    ("psiquiatricas", "Psiquiátricas"),
                    ("geneticas", "Genéticas"),
                    ("outra", "Outra"),
                ],
                default=1,
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
