# Generated by Django 4.2.7 on 2023-11-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_paciente_estadocivil_alter_consulta_atendimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="NomeCompleto",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
